import React,{useEffect,useState}from'react';
import{View,Text,TextInput,Button,ScrollView,StyleSheet}from'react-native';
import*as Location from'expo-location';
import AsyncStorage from'@react-native-async-storage/async-storage';

const API=process.env.EXPO_PUBLIC_API_URL||'http://127.0.0.1:3000';
const KEY='bluecarbon_field_queue';

export default function App(){
 const[p,setP]=useState({name:'Field Mangrove Project',ecosystem:'Mangrove',location:'',area_hectares:'',latitude:'',longitude:'',gps_accuracy_m:'',captured_at:'',evidence_hash:''});
 const[q,setQ]=useState([]),[msg,setMsg]=useState(''),[gpsBusy,setGpsBusy]=useState(false),[samples,setSamples]=useState(0);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>x&&setQ(JSON.parse(x))).catch(()=>{});},[]);
 const persist=async next=>{setQ(next);await AsyncStorage.setItem(KEY,JSON.stringify(next));};
 const getGPS=async()=>{setGpsBusy(true);setMsg('Requesting high-accuracy GPS…');try{const{status}=await Location.requestForegroundPermissionsAsync();if(status!=='granted')throw Error('Location permission denied');const a=[];for(let i=0;i<3;i++){const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Highest});a.push(l);setSamples(i+1);if(i<2)await new Promise(r=>setTimeout(r,700));}const lat=a.reduce((s,x)=>s+x.coords.latitude,0)/a.length;const lon=a.reduce((s,x)=>s+x.coords.longitude,0)/a.length;const acc=Math.min(...a.map(x=>x.coords.accuracy??9999));const captured=new Date().toISOString();setP(v=>({...v,latitude:lat.toFixed(6),longitude:lon.toFixed(6),gps_accuracy_m:acc.toFixed(1),captured_at:captured}));setMsg(`GPS locked • ±${acc.toFixed(1)} m • 3 samples`);}catch(e){setMsg(`GPS failed: ${e.message}`)}finally{setGpsBusy(false);setSamples(0)}};
 const validate=async()=>{try{const r=await fetch(`${API}/api/gps/validate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),x=await r.json();setMsg(r.ok?`GPS valid • ${x.latitude}, ${x.longitude} • ±${x.accuracy_m} m`:`GPS invalid • ${x.errors?.join('; ')||x.detail}`)}catch{setMsg('Backend unavailable — GPS remains stored locally')}};
 const offline=async()=>{const next=[...q,{...p,queued_at:new Date().toISOString()}];await persist(next);setMsg(`Offline upload pack saved (${next.length})`)};
 const sync=async()=>{try{const r=await fetch(`${API}/api/offline/sync`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pack:{projects:q,evidence:[]}})});if(!r.ok)throw Error();await persist([]);setMsg('Offline pack synced');}catch{setMsg('No network — pack remains safely queued')}};
 return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>BlueCarbon Field App</Text><Text style={s.sub}>GPS • Geotagged evidence • Offline • Low bandwidth</Text><View style={s.card}><Text style={s.head}>Field project</Text>{Object.entries(p).map(([k,v])=><TextInput key={k} style={s.input} placeholder={k.replaceAll('_',' ')} placeholderTextColor="#789087" value={String(v)} onChangeText={z=>setP(x=>({...x,[k]:z}))}/>}<Button title={gpsBusy?`Sampling ${samples}/3`:'Capture 3 high-accuracy GPS samples'} onPress={getGPS} disabled={gpsBusy}/><View style={s.gap}/><Button title="Validate GPS with server" onPress={validate}/><View style={s.gap}/><Button title="Save offline upload pack" onPress={offline}/><View style={s.gap}/><Button title={`Sync ${q.length} queued pack(s)`} onPress={sync}/><Text style={s.msg}>{msg}</Text></View><Text style={s.note}>GPS record contains latitude, longitude, reported accuracy and capture timestamp. The web workflow additionally binds the evidence SHA-256 to this GPS metadata. Browser/mobile GPS requires location permission; deployed web clients should use HTTPS.</Text></ScrollView>}
const s=StyleSheet.create({page:{padding:22,backgroundColor:'#06110d',minHeight:'100%',gap:10},title:{fontSize:30,fontWeight:'800',color:'#eaf5ef',marginTop:35},sub:{color:'#8fc5a9',marginBottom:10},card:{backgroundColor:'#0b1c16',padding:16,borderRadius:12,borderWidth:1,borderColor:'#294d3c'},head:{fontSize:18,fontWeight:'700',color:'#eaf5ef',marginBottom:10},input:{backgroundColor:'#10251d',borderColor:'#294d3c',borderWidth:1,borderRadius:9,padding:12,color:'#fff',marginBottom:9},gap:{height:5},msg:{color:'#a8efc6',marginTop:12},note:{color:'#7f968b',fontSize:12,lineHeight:18,marginTop:15}});