import React,{useEffect,useState}from'react';
import{View,Text,TextInput,Button,ScrollView,StyleSheet,Image}from'react-native';
import*as Location from'expo-location';
import*as ImagePicker from'expo-image-picker';
import AsyncStorage from'@react-native-async-storage/async-storage';
const API=process.env.EXPO_PUBLIC_API_URL||'http://127.0.0.1:3000';const KEY='bluecarbon_field_queue';
export default function App(){
 const[p,setP]=useState({name:'Field Mangrove Project',ecosystem:'Mangrove',location:'',area_hectares:'10',latitude:'',longitude:'',gps_accuracy_m:'',captured_at:'',evidence_hash:'',capture_proof_hash:'',offline_id:''});const[q,setQ]=useState([]),[photo,setPhoto]=useState(null),[msg,setMsg]=useState(''),[gpsBusy,setGpsBusy]=useState(false),[samples,setSamples]=useState(0),[busy,setBusy]=useState(false);
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>x&&setQ(JSON.parse(x))).catch(()=>{})},[]);const persist=async x=>{setQ(x);await AsyncStorage.setItem(KEY,JSON.stringify(x))};
 const getGPS=async()=>{setGpsBusy(true);setMsg('Requesting high-accuracy GPS…');try{const{status}=await Location.requestForegroundPermissionsAsync();if(status!=='granted')throw Error('Location permission denied');const a=[];for(let i=0;i<3;i++){a.push(await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Highest}));setSamples(i+1);if(i<2)await new Promise(r=>setTimeout(r,700))}const latitude=a.reduce((s,x)=>s+x.coords.latitude,0)/a.length,longitude=a.reduce((s,x)=>s+x.coords.longitude,0)/a.length,accuracy=Math.min(...a.map(x=>x.coords.accuracy??9999));const captured_at=new Date().toISOString();setP(v=>({...v,latitude:latitude.toFixed(6),longitude:longitude.toFixed(6),gps_accuracy_m:accuracy.toFixed(1),captured_at}));setMsg(`GPS locked • ±${accuracy.toFixed(1)} m • 3 samples`)}catch(e){setMsg(`GPS failed: ${e.message}`)}finally{setGpsBusy(false);setSamples(0)}};
 const validate=async()=>{try{const r=await fetch(`${API}/api/gps/validate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const x=await r.json();setMsg(r.ok?`GPS valid • ${x.latitude}, ${x.longitude} • ±${x.accuracy_m??'—'} m`:`GPS invalid • ${x.errors?.join('; ')||x.detail}`)}catch{setMsg('Backend unavailable')}};
 const camera=async()=>{try{const perm=await ImagePicker.requestCameraPermissionsAsync();if(perm.status!=='granted')throw Error('Camera permission denied');const x=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.8});if(!x.canceled)setPhoto(x.assets[0])}catch(e){setMsg(`Camera failed: ${e.message}`)}};
 const hashEvidence=async()=>{if(!photo)throw Error('Capture a field photo first');if(!p.latitude||!p.longitude||!p.captured_at)throw Error('Capture GPS before evidence');setBusy(true);try{const f=new FormData();f.append('file',{uri:photo.uri,name:`field-${Date.now()}.jpg`,type:'image/jpeg'});f.append('latitude',p.latitude);f.append('longitude',p.longitude);f.append('gps_accuracy_m',p.gps_accuracy_m);f.append('captured_at',p.captured_at);const r=await fetch(`${API}/api/evidence/hash`,{method:'POST',body:f});const x=await r.json();if(!r.ok)throw Error(x.detail||'Evidence hash failed');setP(v=>({...v,evidence_hash:x.sha256,capture_proof_hash:x.capture_proof_hash}));setMsg(`Photo SHA-256 created • ${x.sha256.slice(0,18)}…`)}catch(e){setMsg(`Evidence failed: ${e.message}`)}finally{setBusy(false)}};
 const submit=async()=>{if(!p.evidence_hash)throw Error('Hash the field photo first');setBusy(true);try{const offline_id=p.offline_id||`${Date.now()}-${Math.random().toString(36).slice(2)}`;const r=await fetch(`${API}/api/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...p,offline_id,area_hectares:Number(p.area_hectares)})});const x=await r.json();if(!r.ok)throw Error(x.detail||'Project submission failed');setP(v=>({...v,offline_id}));setMsg(`Project #${x.id} submitted for verification`)}catch(e){setMsg(`Submit failed: ${e.message}`)}finally{setBusy(false)}};
 const offline=async()=>{const x={...p,offline_id:p.offline_id||`${Date.now()}-${Math.random().toString(36).slice(2)}`,queued_at:new Date().toISOString(),photo_uri:photo?.uri||''};const next=[...q,x];await persist(next);setP(v=>({...v,offline_id:x.offline_id}));setMsg(`Offline upload pack saved (${next.length})`)};
 const sync=async()=>{if(!q.length)return setMsg('No offline packs queued');setBusy(true);try{const r=await fetch(`${API}/api/offline/sync`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pack:{projects:q,evidence:[]}})});const x=await r.json();if(!r.ok)throw Error(x.detail||'Sync failed');await persist([]);setMsg(`Offline sync complete • ${x.items} items`)}catch(e){setMsg(`No network — queue retained (${e.message})`)}finally{setBusy(false)}};
 return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>BlueCarbon Field App</Text><Text style={s.sub}>GPS • Photo evidence • Offline • Low bandwidth</Text><View style={s.card}><Text style={s.head}>Field project</Text><TextInput style={s.input} placeholder="Project name" placeholderTextColor="#789087" value={p.name} onChangeText={v=>setP({...p,name:v})}/><TextInput style={s.input} placeholder="Ecosystem" placeholderTextColor="#789087" value={p.ecosystem} onChangeText={v=>setP({...p,ecosystem:v})}/><TextInput style={s.input} placeholder="Location" placeholderTextColor="#789087" value={p.location} onChangeText={v=>setP({...p,location:v})}/><TextInput style={s.input} placeholder="Area hectares" placeholderTextColor="#789087" keyboardType="decimal-pad" value={String(p.area_hectares)} onChangeText={v=>setP({...p,area_hectares:v})}/><Button title={gpsBusy?`Sampling ${samples}/3`:'Capture 3 high-accuracy GPS samples'} onPress={getGPS} disabled={gpsBusy}/><View style={s.gap}/><Text style={s.gps}>📍 {p.latitude||'—'}, {p.longitude||'—'} · ±{p.gps_accuracy_m||'—'} m</Text><Text style={s.gps}>{p.captured_at||'GPS not captured'}</Text><Button title="Validate GPS" onPress={validate}/><View style={s.gap}/><Button title="Capture timestamped field photo" onPress={camera}/>{photo&&<Image source={{uri:photo.uri}} style={s.photo}/>}<View style={s.gap}/><Button title="Hash + bind photo to GPS" onPress={hashEvidence} disabled={busy}/><View style={s.gap}/><Button title="Submit project online" onPress={submit} disabled={busy}/><View style={s.gap}/><Button title="Save offline upload pack" onPress={offline}/><View style={s.gap}/><Button title={`Sync ${q.length} offline pack(s)`} onPress={sync} disabled={busy}/><Text style={s.msg}>{msg}</Text></View><Text style={s.note}>For a physical phone, set EXPO_PUBLIC_API_URL to the computer's LAN address, for example http://192.168.1.10:3000. Production deployments should use HTTPS. GPS/photo evidence is metadata/provenance and does not by itself certify ecological measurements.</Text></ScrollView>}
const s=StyleSheet.create({page:{padding:22,backgroundColor:'#06110d',minHeight:'100%',gap:10},title:{fontSize:30,fontWeight:'800',color:'#eaf5ef',marginTop:35},sub:{color:'#8fc5a9',marginBottom:10},card:{backgroundColor:'#0b1c16',padding:16,borderRadius:12,borderWidth:1,borderColor:'#294d3c'},head:{fontSize:18,fontWeight:'700',color:'#eaf5ef',marginBottom:10},input:{backgroundColor:'#10251d',borderColor:'#294d3c',borderWidth:1,borderRadius:9,padding:12,color:'#fff',marginBottom:9},gap:{height:6},gps:{color:'#a8efc6',marginVertical:3},photo:{width:'100%',height:220,borderRadius:10,marginTop:10},msg:{color:'#a8efc6',marginTop:12},note:{color:'#7f968b',fontSize:12,lineHeight:18,marginTop:15}});