import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{connectRegistry,gpsChainArgs}from'./blockchain';
import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:3000';
const blankMRV={project_id:'',reporting_year:new Date().getFullYear(),biomass_tonnes_per_hectare:10,soil_carbon_tonnes_per_hectare:50,permanence_factor:.9,latitude:'',longitude:'',gps_accuracy_m:'',captured_at:'',evidence_hash:''};
const tr={en:{title:'BlueCarbon Registry',sub:'Hybrid MRV • Digital Intelligence + On-Ground Human Validation'},hi:{title:'ब्लू कार्बन रजिस्ट्री',sub:'हाइब्रिड MRV • डिजिटल जांच + स्थल सत्यापन'},mr:{title:'ब्लू कार्बन रजिस्ट्री',sub:'हायब्रिड MRV • डिजिटल तपासणी + प्रत्यक्ष पडताळणी'}};
const json=async r=>{const x=await r.json().catch(()=>({detail:'Invalid server response'}));if(!r.ok)throw Error(x.detail||x.message||'Request failed');return x};
function App(){
 const[role,setRole]=useState('NGO'),[tab,setTab]=useState('dashboard'),[lang,setLang]=useState('en'),[data,setData]=useState({projects:[],mrv:[],users:[],disputes:[],sensors:[],audit:[],notifications:[],dashboard:{}}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[account,setAccount]=useState(''),[file,setFile]=useState(null),[gps,setGps]=useState(null),[samples,setSamples]=useState(0),[project,setProject]=useState({name:'Demo Mangrove Restoration',ecosystem:'Mangrove',location:'Maharashtra Coast',area_hectares:10,latitude:'',longitude:'',gps_accuracy_m:'',captured_at:'',evidence_hash:'',capture_proof_hash:'',ipfs_cid:'',offline_id:''}),[mrv,setMrv]=useState(blankMRV),[calc,setCalc]=useState(null),[selected,setSelected]=useState([]),[reg,setReg]=useState({name:'',phone:'',role:'NGO',language:'en',otp_verified:false}),[otp,setOtp]=useState(''),[sensor,setSensor]=useState({sensor_id:'SIM-SENSOR-01',project_id:'',metric:'soil_moisture',value:45,unit:'%'}),[dispute,setDispute]=useState({project_id:'',mrv_id:'',raised_by:'demo-user',reason:''}),[kycRef,setKycRef]=useState('');
 const t=tr[lang];
 const refresh=async()=>{try{const names=['projects','mrv','dashboard','notifications','disputes','audit','sensors','users'];const vals=await Promise.all(names.map(x=>fetch(`${API}/api/${x}`).then(json)));setData({projects:vals[0],mrv:vals[1],dashboard:vals[2],notifications:vals[3],disputes:vals[4],audit:vals[5],sensors:vals[6],users:vals[7]});if(!mrv.project_id&&vals[0][0])setMrv(v=>({...v,project_id:vals[0][0].id}));}catch(e){setMsg(`Backend unavailable: ${e.message}`)}};
 useEffect(()=>{refresh();const timer=setInterval(refresh,10000);return()=>clearInterval(timer)},[]);
 const run=async fn=>{setBusy(true);try{await fn()}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const readGPS=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('Browser geolocation is unavailable'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0})});
 const captureGPS=()=>run(async()=>{setMsg('Acquiring high-accuracy GPS; keep the device still…');const a=[];for(let i=0;i<3;i++){a.push(await readGPS());setSamples(i+1);if(i<2)await new Promise(r=>setTimeout(r,700))}const latitude=a.reduce((s,x)=>s+x.coords.latitude,0)/a.length,longitude=a.reduce((s,x)=>s+x.coords.longitude,0)/a.length,accuracy=Math.min(...a.map(x=>x.coords.accuracy??9999)),captured_at=new Date().toISOString();const g={latitude:+latitude.toFixed(6),longitude:+longitude.toFixed(6),accuracy_m:+accuracy.toFixed(1),captured_at,samples:3};setGps(g);setProject(v=>({...v,...g,gps_accuracy_m:g.accuracy_m}));setMrv(v=>({...v,...g,gps_accuracy_m:g.accuracy_m}));setMsg(`GPS locked • ±${g.accuracy_m} m • 3 samples`)});
 const validateGPS=()=>run(async()=>{const x=await json(await fetch(`${API}/api/gps/validate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)}));setMsg(`GPS valid • ${x.latitude}, ${x.longitude} • ±${x.accuracy_m??'not reported'} m${x.warnings.length?' • warnings: '+x.warnings.join(', '):''}`)});
 const hashEvidence=()=>run(async()=>{if(!file)throw Error('Select an image/PDF first');const f=new FormData();f.append('file',file);['latitude','longitude','gps_accuracy_m','captured_at'].forEach(k=>f.append(k,String(project[k]??'')));const x=await json(await fetch(`${API}/api/evidence/hash`,{method:'POST',body:f}));setProject(v=>({...v,evidence_hash:x.sha256,capture_proof_hash:x.capture_proof_hash}));setMrv(v=>({...v,evidence_hash:x.sha256}));setMsg(`Evidence hashed and bound to GPS • ${x.sha256.slice(0,18)}…`)});
 const pinIPFS=()=>run(async()=>{if(!file)throw Error('Select an image/PDF first');const f=new FormData();f.append('file',file);const x=await json(await fetch(`${API}/api/evidence/ipfs`,{method:'POST',body:f}));setProject(v=>({...v,ipfs_cid:x.ipfs_cid,evidence_hash:x.sha256}));setMsg(`Evidence pinned to IPFS • CID ${x.ipfs_cid}`)});
 const createProject=e=>run(async()=>{e.preventDefault();if(!project.latitude||!project.longitude||!project.captured_at)throw Error('Capture GPS before creating a project');const offline_id=project.offline_id||crypto.randomUUID();const x=await json(await fetch(`${API}/api/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...project,offline_id,area_hectares:+project.area_hectares})}));setProject(v=>({...v,offline_id}));setMrv(v=>({...v,project_id:x.id,latitude:x.latitude,longitude:x.longitude,gps_accuracy_m:x.gps_accuracy_m,captured_at:x.captured_at,evidence_hash:x.evidence?.hash||v.evidence_hash}));setMsg(`Project #${x.id} created; verification requested`);await refresh()});
 const normalMRV=()=>({...mrv,project_id:Number(mrv.project_id),reporting_year:Number(mrv.reporting_year),biomass_tonnes_per_hectare:Number(mrv.biomass_tonnes_per_hectare),soil_carbon_tonnes_per_hectare:Number(mrv.soil_carbon_tonnes_per_hectare),permanence_factor:Number(mrv.permanence_factor),latitude:Number(mrv.latitude),longitude:Number(mrv.longitude),gps_accuracy_m:Number(mrv.gps_accuracy_m)});
 const calculate=()=>run(async()=>{const x=await json(await fetch(`${API}/api/mrv/calculate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(normalMRV())}));setCalc(x);setMsg('Digital MRV checks completed')});
 const submitMRV=()=>run(async()=>{const x=await json(await fetch(`${API}/api/mrv`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(normalMRV())}));setMsg(`MRV #${x.id} submitted to verifier`);await refresh()});
 const review=async(id,decision)=>run(async()=>{const comments=window.prompt(`${decision} — human validation comments`,'On-ground validation completed');if(!comments)return;await json(await fetch(`${API}/api/mrv/${id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({verifier:account||'human-verifier',decision,comments})}));setMsg(`MRV #${id} ${decision}`);await refresh()});
 const batchQueue=()=>run(async()=>{const x=await json(await fetch(`${API}/api/mrv/batch-verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected})}));setMsg(`Batch #${x.id} queued for ${x.count} MRVs`);setSelected([]);await refresh()});
 const batchProcess=decision=>run(async()=>{if(!selected.length)throw Error('Select submitted MRVs first');const x=await json(await fetch(`${API}/api/mrv/batch-verify/process`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected,decision,comments:'Batch human validation completed',verifier:account||'batch-verifier'})}));setMsg(`Batch processed: ${x.processed} MRVs`);setSelected([]);await refresh()});
 const anchorProject=()=>run(async()=>{const{contract,account:a}=await connectRegistry();setAccount(a);const chainId=await contract.nextProjectId();const tx=await contract.registerProject(project.name,project.ecosystem,project.location,project.evidence_hash||project.capture_proof_hash||'pending');await tx.wait();if(project.capture_proof_hash){const[gLat,gLon,gAcc,gTime,gHash]=gpsChainArgs({latitude:project.latitude,longitude:project.longitude,accuracy_m:project.gps_accuracy_m,captured_at:project.captured_at,proofHash:project.capture_proof_hash});const geoTx=await contract.anchorProjectGPS(chainId,gLat,gLon,gAcc,gTime,gHash);await geoTx.wait();setMsg(`Project + GPS proof anchored on-chain • #${chainId}`)}else setMsg(`Project anchored on-chain • #${chainId}`)});
 const anchorMRV=()=>run(async()=>{if(!mrv.project_id)throw Error('Select a project');if(!mrv.evidence_hash)throw Error('Evidence SHA-256 required');if(!mrv.latitude||!mrv.longitude||!mrv.captured_at)throw Error('MRV GPS proof required');const{contract,account:a}=await connectRegistry();setAccount(a);const chainMRV=await contract.nextMRVId();const credits=BigInt(Math.max(1,Math.round(calc?.indicative_carbon_tonnes||1)));const tx=await contract.submitMRV(Number(mrv.project_id),mrv.evidence_hash,credits);await tx.wait();const proof=mrv.evidence_hash;const[gLat,gLon,gAcc,gTime,gHash]=gpsChainArgs({latitude:mrv.latitude,longitude:mrv.longitude,accuracy_m:mrv.gps_accuracy_m,captured_at:mrv.captured_at,proofHash:proof});const geoTx=await contract.anchorMRVGPS(chainMRV,gLat,gLon,gAcc,gTime,gHash);await geoTx.wait();setMsg(`MRV + GPS proof anchored on-chain • #${chainMRV}`)});
 const offlineSave=()=>{const q=JSON.parse(localStorage.getItem('bluecarbon_queue')||'[]');const x={...project,offline_id:project.offline_id||crypto.randomUUID(),queued_at:new Date().toISOString()};q.push(x);localStorage.setItem('bluecarbon_queue',JSON.stringify(q));setProject(v=>({...v,offline_id:x.offline_id}));setMsg(`Offline pack saved locally (${q.length})`)};
 const offlineSync=()=>run(async()=>{const q=JSON.parse(localStorage.getItem('bluecarbon_queue')||'[]');if(!q.length)throw Error('No offline packs queued');const x=await json(await fetch(`${API}/api/offline/sync`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pack:{projects:q,evidence:[]}})}));if(x.synced)localStorage.removeItem('bluecarbon_queue');setMsg(`Offline sync complete • ${x.items} items processed`);await refresh()});
 const requestOTP=()=>run(async()=>{const x=await json(await fetch(`${API}/api/auth/request-otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:reg.phone})}));setMsg(x.delivery==='sms'?'OTP sent by SMS':`Demo OTP: ${x.demo_otp}`)});
 const verifyOTP=()=>run(async()=>{await json(await fetch(`${API}/api/auth/verify-otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:reg.phone,code:otp})}));setReg(v=>({...v,otp_verified:true}));setMsg('Phone OTP verified')});
 const registerUser=()=>run(async()=>{if(!reg.otp_verified)throw Error('Verify OTP before registration');await json(await fetch(`${API}/api/users`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(reg)}));setMsg('User registered; KYC is pending');await refresh()});
 const kyc=(id,status)=>run(async()=>{await json(await fetch(`${API}/api/users/${id}/kyc`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kyc_status:status,kyc_reference:kycRef})}));setMsg(`KYC ${status.toLowerCase()}`);await refresh()});
 const ingestSensor=()=>run(async()=>{const x=await json(await fetch(`${API}/api/sensors/readings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...sensor,project_id:Number(sensor.project_id)||null,value:Number(sensor.value)})}));setMsg(x.alerts?.length?`IoT alert generated: ${x.alerts.join(', ')}`:'IoT reading recorded');await refresh()});
 const openDispute=()=>run(async()=>{await json(await fetch(`${API}/api/disputes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...dispute,project_id:Number(dispute.project_id)||null,mrv_id:Number(dispute.mrv_id)||null})}));setMsg('Dispute opened and notification generated');await refresh()});
 const updateDispute=(id,status)=>run(async()=>{await json(await fetch(`${API}/api/disputes/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,resolution:status==='RESOLVED'?'Admin resolution recorded':''})}));setMsg(`Dispute #${id} updated`);await refresh()});
 const pending=data.mrv.filter(x=>x.status==='SUBMITTED');const queued=useMemo(()=>{try{return JSON.parse(localStorage.getItem('bluecarbon_queue')||'[]').length}catch{return 0}},[msg]);
 return <div className="page"><header><div><span className="eyebrow">SIH25038 · CLEAN & GREEN · SOFTWARE</span><h1>{t.title}</h1><p>{t.sub}</p></div><div className="top"><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">EN</option><option value="hi">हिं</option><option value="mr">मर</option></select><span className="badge">{account?account.slice(0,6)+'…'+account.slice(-4):role}</span></div></header>
 <div className="featurebar"><b>Full workflow</b><span>GPS</span><span>Geotagged evidence</span><span>SHA-256</span><span>IPFS</span><span>Digital MRV</span><span>Human validation</span><span>Blockchain</span><span>Offline ({queued})</span><span>OTP/KYC</span><span>IoT</span><span>Disputes</span><span>Batch verification</span></div>
 <nav className="roles">{['NGO','VERIFIER','ADMIN'].map(x=><button key={x} className={role===x?'active':''} onClick={()=>setRole(x)}>{x}</button>)}{['dashboard','projects','mrv','registry','users','disputes','sensors','audit','notifications'].map(x=><button key={x} className={tab===x?'active secondary':''} onClick={()=>setTab(x)}>{x}</button>)}<button onClick={()=>run(refresh)}>Refresh</button><button onClick={offlineSync}>Sync offline</button></nav>
 <section className="stats"><div><small>Projects</small><strong>{data.dashboard.projects||0}</strong></div><div><small>Area</small><strong>{(+data.dashboard.area_hectares||0).toFixed(1)} ha</strong></div><div><small>Pending MRV</small><strong>{data.dashboard.pending_verification||0}</strong></div><div><small>Verified carbon</small><strong>{(+data.dashboard.verified_carbon_tonnes||0).toFixed(1)} tCO₂e</strong></div><div><small>Alerts</small><strong>{data.notifications.length}</strong></div></section>
 {tab==='dashboard'&&<section className="card full"><h2>Operational control centre</h2><div className="adminGrid"><div><b>Hybrid MRV</b><p>Automated digital checks assist; human/on-ground validation decides approval.</p></div><div><b>Evidence integrity</b><p>SHA-256 + GPS coordinates + accuracy + timestamp + optional IPFS CID.</p></div><div><b>Field resilience</b><p>Browser/mobile GPS capture, persistent offline packs and low-bandwidth synchronisation.</p></div><div><b>Governance</b><p>Roles, OTP, KYC status, disputes, notifications and blockchain anchoring.</p></div></div><div className="capabilities"><b>Scientific boundary:</b> the carbon calculation is an illustrative prototype estimate, not a certified carbon-credit methodology. Real issuance requires an approved methodology, independent verification and applicable registry rules.</div></section>}
 {tab==='projects'&&<section className="card full"><h2>NGO/Panchayat · Project + evidence capture</h2><form onSubmit={createProject}><div className="grid2"><input value={project.name} onChange={e=>setProject({...project,name:e.target.value})} placeholder="Project name"/><select value={project.ecosystem} onChange={e=>setProject({...project,ecosystem:e.target.value})}><option>Mangrove</option><option>Seagrass</option><option>Salt Marsh</option><option>Tidal Wetland</option></select><input value={project.location} onChange={e=>setProject({...project,location:e.target.value})} placeholder="Location"/><input type="number" min=".1" value={project.area_hectares} onChange={e=>setProject({...project,area_hectares:e.target.value})} placeholder="Area hectares"/></div><div className="gpsbox card"><b>📍 GPS field proof</b><p className="muted">Three high-accuracy readings are averaged. Server validation checks coordinate ranges, timestamp, accuracy and stale/future captures.</p><div className="inline"><input value={project.latitude} onChange={e=>setProject({...project,latitude:e.target.value})} placeholder="Latitude"/><input value={project.longitude} onChange={e=>setProject({...project,longitude:e.target.value})} placeholder="Longitude"/><button type="button" onClick={captureGPS} disabled={busy}>{samples?`Sampling ${samples}/3`:'Capture 3 GPS samples'}</button></div><div className="inline"><span className="badge">Accuracy ±{project.gps_accuracy_m||'—'} m</span><span className="badge">{project.captured_at?new Date(project.captured_at).toLocaleString():'Not captured'}</span><button type="button" onClick={validateGPS}>Validate GPS</button></div></div><input type="file" accept="image/*,.pdf" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="inline"><button type="button" onClick={hashEvidence}>SHA-256 + geotag</button><button type="button" onClick={pinIPFS}>Pin evidence to IPFS</button><button type="button" onClick={offlineSave}>Save offline pack</button><button type="submit">Create project</button><button type="button" onClick={anchorProject}>Anchor project + GPS on-chain</button></div>{project.evidence_hash&&<div className="proof"><span>Evidence SHA-256: {project.evidence_hash}</span><span>GPS proof: {project.capture_proof_hash||'—'}</span><span>IPFS CID: {project.ipfs_cid||'not pinned'}</span></div>}</form></section>}
 {tab==='mrv'&&<section className="card full"><h2>Measurement, Reporting & Verification</h2><div className="grid2"><select value={mrv.project_id} onChange={e=>{const z=data.projects.find(x=>x.id===Number(e.target.value));setMrv(v=>({...v,project_id:e.target.value,latitude:z?.latitude||v.latitude,longitude:z?.longitude||v.longitude,gps_accuracy_m:z?.gps_accuracy_m||v.gps_accuracy_m,captured_at:z?.captured_at||v.captured_at,evidence_hash:z?.evidence?.hash||v.evidence_hash}))}}><option value="">Select project</option>{data.projects.map(x=><option key={x.id} value={x.id}>#{x.id} {x.name}</option>)}</select><input type="number" value={mrv.reporting_year} onChange={e=>setMrv({...mrv,reporting_year:e.target.value})} placeholder="Reporting year"/><input type="number" min="0" value={mrv.biomass_tonnes_per_hectare} onChange={e=>setMrv({...mrv,biomass_tonnes_per_hectare:e.target.value})} placeholder="Biomass t/ha"/><input type="number" min="0" value={mrv.soil_carbon_tonnes_per_hectare} onChange={e=>setMrv({...mrv,soil_carbon_tonnes_per_hectare:e.target.value})} placeholder="Soil carbon t/ha"/><input type="number" min="0" max="1" step=".01" value={mrv.permanence_factor} onChange={e=>setMrv({...mrv,permanence_factor:e.target.value})} placeholder="Permanence factor"/><input value={mrv.evidence_hash} onChange={e=>setMrv({...mrv,evidence_hash:e.target.value})} placeholder="Evidence SHA-256"/></div><div className="gpsmeta"><span>GPS: {mrv.latitude||'—'}, {mrv.longitude||'—'}</span><span>Accuracy ±{mrv.gps_accuracy_m||'—'} m</span><span>{mrv.captured_at||'—'}</span></div><div className="inline"><button onClick={calculate}>Run digital checks</button><button onClick={submitMRV}>Request human verification</button><button onClick={anchorMRV}>Anchor MRV + GPS on-chain</button></div>{calc&&<div className="result"><b>{calc.indicative_carbon_tonnes} tCO₂e indicative</b><span>Risk: {calc.digital_intelligence.risk}</span><span>GPS: {calc.gps_validation.valid?'VALID':'INVALID'} · {calc.digital_intelligence.flags.join(' · ')||'No automated flags'}</span><small>{calc.disclaimer}</small></div>}</section>}
 {role==='VERIFIER'&&<section className="card full"><h2>Verifier queue + batch verification</h2>{pending.map(x=><div className="review" key={x.id}><div><label><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,x.id]:v.filter(i=>i!==x.id))}/> <b>MRV #{x.id}</b></label><span>Project #{x.project_id} · {x.indicative_carbon_tonnes} tCO₂e</span><span>📍 {x.latitude} / {x.longitude} · ±{x.gps_accuracy_m} m · {x.captured_at}</span><span>Evidence: {x.evidence_hash?'present':'missing'} · Digital risk: {x.digital_intelligence?.risk}</span></div><div className="inline"><button onClick={()=>review(x.id,'APPROVE')}>Approve</button><button onClick={()=>review(x.id,'REJECT')}>Reject</button></div></div>)}{!pending.length&&<p className="muted">No pending MRVs.</p>}<div className="inline"><button onClick={batchQueue} disabled={!selected.length}>Queue selected batch</button><button onClick={()=>batchProcess('APPROVE')} disabled={!selected.length}>Approve selected</button><button onClick={()=>batchProcess('REJECT')} disabled={!selected.length}>Reject selected</button></div></section>}
 {tab==='registry'&&<section className="card full"><h2>Public registry</h2>{data.projects.map(x=><div className="row" key={x.id}><div><b>#{x.id} {x.name}</b><small>{x.ecosystem} · {x.location} · {x.area_hectares} ha</small><small>📍 {x.latitude},{x.longitude} · ±{x.gps_accuracy_m??'—'} m · {x.captured_at}</small><small>Evidence: {x.evidence?.hash?'SHA-256 bound':'missing'} · IPFS: {x.evidence?.ipfs_cid||'—'}</small></div><span className="status">{x.status}</span></div>)}</section>}
 {tab==='users'&&<section className="card full"><h2>User registration · OTP · KYC</h2><div className="grid2"><input placeholder="Name" value={reg.name} onChange={e=>setReg({...reg,name:e.target.value})}/><input placeholder="Phone" value={reg.phone} onChange={e=>setReg({...reg,phone:e.target.value})}/><select value={reg.role} onChange={e=>setReg({...reg,role:e.target.value})}><option>NGO</option><option>VERIFIER</option><option>ADMIN</option></select><select value={reg.language} onChange={e=>setReg({...reg,language:e.target.value})}><option value="en">English</option><option value="hi">Hindi</option><option value="mr">Marathi</option></select></div><div className="inline"><button onClick={requestOTP}>Request OTP</button><input placeholder="6-digit OTP" value={otp} onChange={e=>setOtp(e.target.value)}/><button onClick={verifyOTP}>Verify OTP</button><button onClick={registerUser}>Register user</button></div><input placeholder="KYC reference (do not enter sensitive documents)" value={kycRef} onChange={e=>setKycRef(e.target.value)}/>{data.users.map(u=><div className="row" key={u.id}><div><b>{u.name}</b><small>{u.role} · phone ending {u.phone.slice(-4)} · OTP {u.otp_verified?'verified':'not verified'}</small></div><span className="status">KYC {u.kyc_status}</span><div className="inline"><button onClick={()=>kyc(u.id,'VERIFIED')}>Verify KYC</button><button onClick={()=>kyc(u.id,'REJECTED')}>Reject</button></div></div>)}</section>}
 {tab==='disputes'&&<section className="card full"><h2>Dispute management</h2><div className="grid2"><select value={dispute.project_id} onChange={e=>setDispute({...dispute,project_id:e.target.value})}><option value="">Project (optional)</option>{data.projects.map(x=><option key={x.id} value={x.id}>#{x.id} {x.name}</option>)}</select><select value={dispute.mrv_id} onChange={e=>setDispute({...dispute,mrv_id:e.target.value})}><option value="">MRV (optional)</option>{data.mrv.map(x=><option key={x.id} value={x.id}>MRV #{x.id}</option>)}</select></div><input placeholder="Reason / dispute details" value={dispute.reason} onChange={e=>setDispute({...dispute,reason:e.target.value})}/><button onClick={openDispute}>Open dispute</button>{data.disputes.map(x=><div className="row" key={x.id}><div><b>Dispute #{x.id}</b><small>Project {x.project_id||'—'} · MRV {x.mrv_id||'—'} · {x.reason}</small></div><span className="status">{x.status}</span><div className="inline"><button onClick={()=>updateDispute(x.id,'IN_REVIEW')}>Review</button><button onClick={()=>updateDispute(x.id,'RESOLVED')}>Resolve</button><button onClick={()=>updateDispute(x.id,'REJECTED')}>Reject</button></div></div>)}</section>}
 {tab==='sensors'&&<section className="card full"><h2>IoT / environmental telemetry</h2><p className="muted">Functional simulator for the PDF's soil-moisture/salinity telemetry pathway. Readings are timestamped, persisted and threshold-checked.</p><div className="grid2"><input value={sensor.sensor_id} onChange={e=>setSensor({...sensor,sensor_id:e.target.value})} placeholder="Sensor ID"/><select value={sensor.project_id} onChange={e=>setSensor({...sensor,project_id:e.target.value})}><option value="">Project</option>{data.projects.map(x=><option key={x.id} value={x.id}>#{x.id} {x.name}</option>)}</select><select value={sensor.metric} onChange={e=>setSensor({...sensor,metric:e.target.value,unit:e.target.value==='soil_moisture'?'%':e.target.value==='salinity'?'ppt':'°C'})}><option value="soil_moisture">Soil moisture</option><option value="salinity">Salinity</option><option value="temperature">Temperature</option></select><input type="number" value={sensor.value} onChange={e=>setSensor({...sensor,value:e.target.value})} placeholder="Value"/><input value={sensor.unit} onChange={e=>setSensor({...sensor,unit:e.target.value})} placeholder="Unit"/></div><button onClick={ingestSensor}>Record sensor reading</button>{data.sensors.map(x=><div className="row" key={x.id}><div><b>{x.sensor_id}</b><small>{x.metric}: {x.value} {x.unit} · {x.captured_at}</small></div><span className="status">{x.alerts?.length?x.alerts.join(', '):'NORMAL'}</span></div>)}</section>}
 {tab==='audit'&&<section className="card full"><h2>Audit trail</h2>{data.audit.map(x=><div className="row" key={x.id}><div><b>#{x.id} · {x.action}</b><small>{x.at} · {JSON.stringify(x.meta)}</small></div></div>)}</section>}
 {tab==='notifications'&&<section className="card full"><h2>Notifications</h2>{data.notifications.map(x=><div className="row" key={x.id}><div><b>{x.type}</b><small>{x.created_at} · {JSON.stringify(x).slice(0,260)}</small></div></div>)}</section>}
 <footer>SIH25038 prototype • API persistence is local JSON • SMS/IPFS/blockchain integrations require their respective configuration. Browser GPS requires HTTPS in deployed environments.</footer>{msg&&<div className="toast">{msg}{busy?' ⏳':''}</div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);