import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{connectRegistry,gpsChainArgs}from'./blockchain';
import'./styles.css';

const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:3000';
const blankMRV={project_id:'',reporting_year:new Date().getFullYear(),biomass_tonnes_per_hectare:10,soil_carbon_tonnes_per_hectare:50,permanence_factor:.9,latitude:'',longitude:'',gps_accuracy_m:'',captured_at:'',evidence_hash:''};
const nav=['dashboard','projects','mrv','registry','training','users','disputes','sensors','audit','notifications'];
const text={
 en:{title:'BlueCarbon Registry',sub:'Hybrid MRV • Digital Intelligence + On-Ground Human Validation',login:'OTP login',register:'Register user',demo:'Demo accounts',phone:'Phone',otp:'OTP',request:'Request OTP',loginBtn:'Login',logout:'Logout',dashboard:'Dashboard',projects:'Projects',mrv:'MRV',registry:'Registry',training:'Training',users:'Users',disputes:'Disputes',sensors:'IoT',audit:'Audit',notifications:'Notifications'},
 hi:{title:'ब्लू कार्बन रजिस्ट्री',sub:'हाइब्रिड MRV • डिजिटल जांच + स्थल सत्यापन',login:'OTP लॉगिन',register:'उपयोगकर्ता पंजीकरण',demo:'डेमो खाते',phone:'फोन',otp:'OTP',request:'OTP मांगें',loginBtn:'लॉगिन',logout:'लॉगआउट',dashboard:'डैशबोर्ड',projects:'प्रोजेक्ट',mrv:'MRV',registry:'रजिस्ट्री',training:'प्रशिक्षण',users:'उपयोगकर्ता',disputes:'विवाद',sensors:'IoT',audit:'ऑडिट',notifications:'सूचनाएं'},
 mr:{title:'ब्लू कार्बन रजिस्ट्री',sub:'हायब्रिड MRV • डिजिटल तपासणी + प्रत्यक्ष पडताळणी',login:'OTP लॉगिन',register:'वापरकर्ता नोंदणी',demo:'डेमो खाती',phone:'फोन',otp:'OTP',request:'OTP मागवा',loginBtn:'लॉगिन',logout:'लॉगआउट',dashboard:'डॅशबोर्ड',projects:'प्रकल्प',mrv:'MRV',registry:'रजिस्ट्री',training:'प्रशिक्षण',users:'वापरकर्ते',disputes:'वाद',sensors:'IoT',audit:'ऑडिट',notifications:'सूचना'}
};
const trainingModules=[
 ['1','Capture a valid field proof','Stand still, capture 3 high-accuracy GPS readings, and keep the timestamp with the evidence.','3 GPS samples + accuracy + timestamp'],
 ['2','Create tamper-evident evidence','Capture a field image/PDF, compress images for low bandwidth, then create SHA-256 bound to the GPS metadata.','Evidence hash + GPS proof hash'],
 ['3','Run digital MRV','Enter measurements, run automated checks, inspect GPS/evidence flags, and submit for human verification.','Digital screening never replaces field verification'],
 ['4','Perform human validation','Verifier reviews evidence, location, measurements and comments, then approves or rejects. Batch review is available for queues.','Human decision + comments + report'],
 ['5','Work offline','Save a local upload pack in the field. Sync it when connectivity returns; duplicate offline IDs are detected.','Offline-first field workflow']
];
const json=async r=>{const x=await r.json().catch(()=>({detail:'Invalid server response'}));if(!r.ok)throw Error(x.detail||x.message||'Request failed');return x};
function App(){
 const[lang,setLang]=useState(localStorage.getItem('bc_lang')||'en'),[tab,setTab]=useState('dashboard'),[user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('bc_user')||'null')}catch{return null}}),[token,setToken]=useState(localStorage.getItem('bc_token')||''),[loginPhone,setLoginPhone]=useState('9999999997'),[loginOtp,setLoginOtp]=useState(''),[loginHint,setLoginHint]=useState(''),[reg,setReg]=useState({name:'',phone:'',role:'NGO',language:'en'}),[regOtp,setRegOtp]=useState(''),[regVerified,setRegVerified]=useState(false),[data,setData]=useState({projects:[],mrv:[],users:[],disputes:[],sensors:[],audit:[],notifications:[],dashboard:{}}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState(null),[project,setProject]=useState({name:'Demo Mangrove Restoration',ecosystem:'Mangrove',location:'Maharashtra Coast',area_hectares:10,latitude:'',longitude:'',gps_accuracy_m:'',captured_at:'',evidence_hash:'',capture_proof_hash:'',ipfs_cid:'',offline_id:''}),[samples,setSamples]=useState(0),[mrv,setMrv]=useState(blankMRV),[calc,setCalc]=useState(null),[selected,setSelected]=useState([]),[sensor,setSensor]=useState({sensor_id:'SIM-SENSOR-01',project_id:'',metric:'soil_moisture',value:45,unit:'%'}),[dispute,setDispute]=useState({project_id:'',mrv_id:'',reason:''}),[kycRef,setKycRef]=useState('');
 const t=text[lang]||text.en;const role=user?.role||'PUBLIC';
 const headers=()=>token?{'X-Session-Token':token}:{};
 const apiFetch=(url,opts={})=>{const h=new Headers(opts.headers||{});if(token)h.set('X-Session-Token',token);return fetch(url,{...opts,headers:h})};
 const refresh=async()=>{try{const publicNames=['projects','mrv','dashboard'];const a=await Promise.all(publicNames.map(x=>fetch(`${API}/api/${x}`).then(json)));let extra={notifications:[],disputes:[],audit:[],sensors:[],users:[]};if(token){const names=['notifications','disputes','audit','sensors'];const v=await Promise.all(names.map(x=>apiFetch(`${API}/api/${x}`).then(json)));extra={...extra,notifications:v[0],disputes:v[1],audit:v[2],sensors:v[3]};if(role==='ADMIN')extra.users=await apiFetch(`${API}/api/users`).then(json)}setData({projects:a[0],mrv:a[1],dashboard:a[2],...extra});if(!mrv.project_id&&a[0][0])setMrv(v=>({...v,project_id:a[0][0].id,latitude:a[0][0].latitude,longitude:a[0][0].longitude,gps_accuracy_m:a[0][0].gps_accuracy_m,captured_at:a[0][0].captured_at,evidence_hash:a[0][0].evidence?.hash||''}))}catch(e){setMsg(`Backend unavailable: ${e.message}`)}};
 useEffect(()=>{localStorage.setItem('bc_lang',lang);if(token)refresh()},[token,lang]);
 const run=async fn=>{setBusy(true);try{await fn()}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const requestLoginOTP=()=>run(async()=>{const x=await json(await fetch(`${API}/api/auth/request-otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:loginPhone,purpose:'login'})}));setLoginHint(x.delivery==='sms'?'OTP sent by SMS':`Demo OTP: ${x.demo_otp}`)});
 const login=()=>run(async()=>{const x=await json(await fetch(`${API}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:loginPhone,code:loginOtp})}));localStorage.setItem('bc_token',x.token);localStorage.setItem('bc_user',JSON.stringify(x.user));setToken(x.token);setUser(x.user);setTab('dashboard');setLoginHint('Logged in successfully')});
 const logout=()=>run(async()=>{await json(await apiFetch(`${API}/api/auth/logout`,{method:'POST'}));localStorage.removeItem('bc_token');localStorage.removeItem('bc_user');setToken('');setUser(null);setTab('dashboard')});
 const requestRegOTP=()=>run(async()=>{const x=await json(await fetch(`${API}/api/auth/request-otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:reg.phone,purpose:'register'})}));setLoginHint(x.delivery==='sms'?'Registration OTP sent by SMS':`Registration demo OTP: ${x.demo_otp}`)});
 const verifyRegOTP=()=>run(async()=>{await json(await fetch(`${API}/api/auth/verify-otp`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:reg.phone,code:regOtp,purpose:'register'})}));setRegVerified(true);setLoginHint('Registration phone verified')});
 const register=()=>run(async()=>{await json(await fetch(`${API}/api/users`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...reg,otp_verified:regVerified})}));setLoginHint('Registered. An admin must verify KYC before OTP login.');setReg({name:'',phone:'',role:'NGO',language:'en'});setRegOtp('');setRegVerified(false)});
 const readGPS=()=>new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('Browser geolocation is unavailable'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0})});
 const captureGPS=()=>run(async()=>{setMsg('Acquiring high-accuracy GPS; keep the device still…');const a=[];for(let i=0;i<3;i++){a.push(await readGPS());setSamples(i+1);if(i<2)await new Promise(r=>setTimeout(r,700))}const latitude=a.reduce((s,x)=>s+x.coords.latitude,0)/3,longitude=a.reduce((s,x)=>s+x.coords.longitude,0)/3,accuracy=Math.min(...a.map(x=>x.coords.accuracy??9999)),captured_at=new Date().toISOString(),g={latitude:+latitude.toFixed(6),longitude:+longitude.toFixed(6),accuracy_m:+accuracy.toFixed(1),captured_at,samples:3};setProject(v=>({...v,...g,gps_accuracy_m:g.accuracy_m}));setMrv(v=>({...v,...g,gps_accuracy_m:g.accuracy_m}));setMsg(`GPS locked • ±${g.accuracy_m} m • 3 samples`)});
 const validateGPS=()=>run(async()=>{const x=await json(await apiFetch(`${API}/api/gps/validate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)}));setMsg(`GPS ${x.valid?'valid':'invalid'} • ${x.latitude}, ${x.longitude} • ±${x.accuracy_m??'not reported'} m${x.warnings.length?' • '+x.warnings.join(', '):''}`)});
 const compressImage=async f=>{if(!f||!f.type.startsWith('image/')||f.size<1500000)return f;const img=new Image();img.src=URL.createObjectURL(f);await new Promise((res,rej)=>{img.onload=res;img.onerror=rej});const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.72));URL.revokeObjectURL(img.src);return new File([blob],f.name.replace(/\.[^.]+$/i,'')+'-compressed.jpg',{type:'image/jpeg'})};
 const chooseFile=e=>run(async()=>{const raw=e.target.files?.[0];if(!raw)return;const z=await compressImage(raw);setFile(z);setMsg(z.size<raw.size?`Image compressed for low bandwidth • ${(raw.size/1024/1024).toFixed(1)} → ${(z.size/1024/1024).toFixed(1)} MB`:`Evidence selected • ${(z.size/1024/1024).toFixed(1)} MB`)});
 const hashEvidence=()=>run(async()=>{if(!file)throw Error('Select an image/PDF first');const f=new FormData();f.append('file',file);['latitude','longitude','gps_accuracy_m','captured_at'].forEach(k=>f.append(k,String(project[k]??'')));const x=await json(await apiFetch(`${API}/api/evidence/hash`,{method:'POST',body:f}));setProject(v=>({...v,evidence_hash:x.sha256,capture_proof_hash:x.capture_proof_hash}));setMrv(v=>({...v,evidence_hash:x.sha256}));setMsg(`SHA-256 created and bound to GPS • ${x.sha256.slice(0,18)}…`)});
 const pinIPFS=()=>run(async()=>{if(!file)throw Error('Select evidence first');const f=new FormData();f.append('file',file);const x=await json(await apiFetch(`${API}/api/evidence/ipfs`,{method:'POST',body:f}));setProject(v=>({...v,ipfs_cid:x.ipfs_cid,evidence_hash:x.sha256}));setMsg(`Evidence pinned to IPFS • ${x.ipfs_cid}`)});
 const createProject=e=>run(async()=>{e.preventDefault();if(!project.latitude||!project.longitude||!project.captured_at)throw Error('Capture GPS before creating a project');const offline_id=project.offline_id||crypto.randomUUID(),x=await json(await apiFetch(`${API}/api/projects`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...project,offline_id,area_hectares:+project.area_hectares})}));setProject(v=>({...v,offline_id}));setMrv(v=>({...v,project_id:x.id,latitude:x.latitude,longitude:x.longitude,gps_accuracy_m:x.gps_accuracy_m,captured_at:x.captured_at,evidence_hash:x.evidence?.hash||v.evidence_hash}));setMsg(`Project #${x.id} created; verification requested`);await refresh()});
 const normalMRV=()=>({...mrv,project_id:Number(mrv.project_id),reporting_year:Number(mrv.reporting_year),biomass_tonnes_per_hectare:Number(mrv.biomass_tonnes_per_hectare),soil_carbon_tonnes_per_hectare:Number(mrv.soil_carbon_tonnes_per_hectare),permanence_factor:Number(mrv.permanence_factor),latitude:Number(mrv.latitude),longitude:Number(mrv.longitude),gps_accuracy_m:Number(mrv.gps_accuracy_m)});
 const calculate=()=>run(async()=>{const x=await json(await apiFetch(`${API}/api/mrv/calculate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(normalMRV())}));setCalc(x);setMsg('Digital MRV + AI-assisted screening completed')});
 const submitMRV=()=>run(async()=>{const x=await json(await apiFetch(`${API}/api/mrv`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(normalMRV())}));setMsg(`MRV #${x.id} submitted for human verification`);await refresh()});
 const review=async(id,decision)=>run(async()=>{const comments=window.prompt(`${decision} — on-ground validation comments`,'On-ground validation completed');if(!comments)return;await json(await apiFetch(`${API}/api/mrv/${id}/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,comments})}));setMsg(`MRV #${id} ${decision}`);await refresh()});
 const batchQueue=()=>run(async()=>{const x=await json(await apiFetch(`${API}/api/mrv/batch-verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected})}));setMsg(`Batch #${x.id} queued • ${x.count} records`);setSelected([]);await refresh()});
 const batchProcess=decision=>run(async()=>{if(!selected.length)throw Error('Select submitted MRVs first');const x=await json(await apiFetch(`${API}/api/mrv/batch-verify/process`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected,decision,comments:'Batch human validation completed'})}));setMsg(`Batch processed • ${x.processed} MRVs`);setSelected([]);await refresh()});
 const anchorProject=()=>run(async()=>{const{contract,account:a}=await connectRegistry();const chainId=await contract.nextProjectId(),tx=await contract.registerProject(project.name,project.ecosystem,project.location,project.evidence_hash||project.capture_proof_hash||'pending');await tx.wait();if(project.capture_proof_hash){const[gLat,gLon,gAcc,gTime,gHash]=gpsChainArgs({latitude:project.latitude,longitude:project.longitude,accuracy_m:project.gps_accuracy_m,captured_at:project.captured_at,proofHash:project.capture_proof_hash});await(await contract.anchorProjectGPS(chainId,gLat,gLon,gAcc,gTime,gHash)).wait()}setMsg(`Project + GPS proof anchored on-chain by ${a.slice(0,8)}…`)});
 const anchorMRV=()=>run(async()=>{if(!mrv.project_id||!mrv.evidence_hash)throw Error('Project and evidence hash are required');const{contract}=await connectRegistry(),chainMRV=await contract.nextMRVId(),credits=BigInt(Math.max(1,Math.round(calc?.indicative_carbon_tonnes||1)));await(await contract.submitMRV(Number(mrv.project_id),mrv.evidence_hash,credits)).wait();const[gLat,gLon,gAcc,gTime,gHash]=gpsChainArgs({latitude:mrv.latitude,longitude:mrv.longitude,accuracy_m:mrv.gps_accuracy_m,captured_at:mrv.captured_at,proofHash:mrv.evidence_hash});await(await contract.anchorMRVGPS(chainMRV,gLat,gLon,gAcc,gTime,gHash)).wait();setMsg(`MRV + GPS proof anchored on-chain • #${chainMRV}`)});
 const offlineSave=()=>{const q=JSON.parse(localStorage.getItem('bluecarbon_queue')||'[]'),x={...project,offline_id:project.offline_id||crypto.randomUUID(),queued_at:new Date().toISOString()};q.push(x);localStorage.setItem('bluecarbon_queue',JSON.stringify(q));setProject(v=>({...v,offline_id:x.offline_id}));setMsg(`Offline upload pack saved • ${q.length} queued`)};
 const offlineSync=()=>run(async()=>{const q=JSON.parse(localStorage.getItem('bluecarbon_queue')||'[]');if(!q.length)throw Error('No offline packs queued');const x=await json(await apiFetch(`${API}/api/offline/sync`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pack:{projects:q,evidence:[]}})}));if(x.synced)localStorage.removeItem('bluecarbon_queue');setMsg(`Offline sync complete • ${x.items} items`);await refresh()});
 const ingestSensor=()=>run(async()=>{const x=await json(await apiFetch(`${API}/api/sensors/readings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...sensor,project_id:Number(sensor.project_id)||null,value:Number(sensor.value)})}));setMsg(x.alerts?.length?`IoT alert: ${x.alerts.join(', ')}`:'IoT reading recorded');await refresh()});
 const openDispute=()=>run(async()=>{await json(await apiFetch(`${API}/api/disputes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...dispute,project_id:Number(dispute.project_id)||null,mrv_id:Number(dispute.mrv_id)||null})}));setMsg('Dispute opened; notification sent');await refresh()});
 const updateDispute=(id,status)=>run(async()=>{await json(await apiFetch(`${API}/api/disputes/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,resolution:status==='RESOLVED'?'Admin resolution recorded':''})}));setMsg(`Dispute #${id} updated`);await refresh()});
 const kyc=(id,status)=>run(async()=>{await json(await apiFetch(`${API}/api/users/${id}/kyc`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kyc_status:status,kyc_reference:kycRef})}));setMsg(`KYC ${status.toLowerCase()}`);await refresh()});
 const report=(kind,id)=>run(async()=>{const r=await apiFetch(`${API}/api/reports/${kind}/${id}`);if(!r.ok)throw Error((await r.text())||'Report failed');const blob=await r.blob(),url=URL.createObjectURL(blob),w=window.open(url,'_blank');if(!w){const a=document.createElement('a');a.href=url;a.download=`bluecarbon-${kind}-${id}.html`;a.click()}setTimeout(()=>URL.revokeObjectURL(url),60000);setMsg(`${kind} report generated`)});
 const completed=useMemo(()=>{try{return JSON.parse(localStorage.getItem('bc_training')||'[]')}catch{return[]}},[msg]);
 const markTraining=n=>{const x=new Set(completed);x.has(n)?x.delete(n):x.add(n);localStorage.setItem('bc_training',JSON.stringify([...x]));setMsg(`Training module ${n} ${x.has(n)?'completed':'reopened'}`)};
 const pending=data.mrv.filter(x=>x.status==='SUBMITTED'),queueCount=(()=>{try{return JSON.parse(localStorage.getItem('bluecarbon_queue')||'[]').length}catch{return 0}})();
 if(!user)return <div className="page"><header><div><span className="eyebrow">SIH25038 · CLEAN & GREEN · SOFTWARE</span><h1>{t.title}</h1><p>{t.sub}</p></div><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">EN</option><option value="hi">हिं</option><option value="mr">मर</option></select></header><div className="loginGrid"><section className="card"><h2>{t.login}</h2><input placeholder={t.phone} value={loginPhone} onChange={e=>setLoginPhone(e.target.value)}/><div className="inline"><button onClick={requestLoginOTP}>{t.request}</button><input placeholder={t.otp} value={loginOtp} onChange={e=>setLoginOtp(e.target.value)}/><button onClick={login}>{t.loginBtn}</button></div><p className="muted">{loginHint}</p><div className="capabilities"><b>{t.demo}</b><br/>Admin: 9999999999 · Verifier: 9999999998 · NGO: 9999999997<br/>Request OTP first; the prototype returns a demo OTP when SMS is not configured.</div></section><section className="card"><h2>{t.register}</h2><div className="grid2"><input placeholder="Name" value={reg.name} onChange={e=>setReg({...reg,name:e.target.value})}/><input placeholder={t.phone} value={reg.phone} onChange={e=>setReg({...reg,phone:e.target.value})}/><select value={reg.role} onChange={e=>setReg({...reg,role:e.target.value})}><option>NGO</option><option>VERIFIER</option><option>ADMIN</option></select><select value={reg.language} onChange={e=>setReg({...reg,language:e.target.value})}><option value="en">English</option><option value="hi">Hindi</option><option value="mr">Marathi</option></select></div><div className="inline"><button onClick={requestRegOTP}>Request OTP</button><input placeholder="OTP" value={regOtp} onChange={e=>setRegOtp(e.target.value)}/><button onClick={verifyRegOTP}>Verify</button><button onClick={register} disabled={!regVerified}>Register</button></div><p className="muted">KYC is intentionally a separate admin approval step.</p></section></div>{msg&&<div className="toast">{msg}{busy?' ⏳':''}</div>}</div>;
 return <div className="page"><header><div><span className="eyebrow">SIH25038 · CLEAN & GREEN · SOFTWARE</span><h1>{t.title}</h1><p>{t.sub}</p></div><div className="top"><select value={lang} onChange={e=>setLang(e.target.value)}><option value="en">EN</option><option value="hi">हिं</option><option value="mr">मर</option></select><span className="badge">{user.name} · {role}</span><button onClick={logout}>{t.logout}</button></div></header><div className="featurebar"><b>Full workflow</b><span>GPS</span><span>Geotagged evidence</span><span>SHA-256</span><span>IPFS</span><span>Digital/AI screening</span><span>Human validation</span><span>Blockchain</span><span>Offline ({queueCount})</span><span>OTP/KYC</span><span>IoT</span><span>Disputes</span><span>Batch verification</span><span>Reports</span></div><nav className="roles">{nav.map(x=><button key={x} className={tab===x?'active secondary':''} onClick={()=>setTab(x)}>{t[x]}</button>)}<button onClick={()=>run(refresh)}>Refresh</button><button onClick={offlineSync}>Sync offline</button></nav><section className="stats"><div><small>Projects</small><strong>{data.dashboard.projects||0}</strong></div><div><small>Area</small><strong>{(+data.dashboard.area_hectares||0).toFixed(1)} ha</strong></div><div><small>Pending MRV</small><strong>{data.dashboard.pending_verification||0}</strong></div><div><small>Verified carbon</small><strong>{(+data.dashboard.verified_carbon_tonnes||0).toFixed(1)} tCO₂e</strong></div><div><small>Alerts</small><strong>{data.notifications.length}</strong></div></section>
 {tab==='dashboard'&&<section className="card full"><h2>Operational control centre</h2><div className="adminGrid"><div><b>Submit evidence</b><p>NGO/Panchayat captures geotagged, timestamped field evidence.</p></div><div><b>Validate data</b><p>GPS, accuracy, timestamp, SHA-256 and digital/AI-assisted screening flag anomalies.</p></div><div><b>Hybrid MRV</b><p>Automated screening assists; on-ground human validation decides approval.</p></div><div><b>Issue registry units</b><p>Verified MRV can be anchored to the Solidity ERC-1155 registry.</p></div></div><div className="capabilities"><b>PDF coverage:</b> transparent blockchain provenance · reliable AI/IoT cross-check pathway · accessible dashboard/mobile workflow · rural offline/low-bandwidth support · status notifications · batch verification · role-based OTP/KYC security.<br/><b>Scientific boundary:</b> the prototype carbon calculation is illustrative and is not a certified credit methodology.</div></section>}
 {tab==='projects'&&<section className="card full"><h2>NGO/Panchayat · Project submission and field evidence</h2><form onSubmit={createProject}><div className="grid2"><input value={project.name} onChange={e=>setProject({...project,name:e.target.value})} placeholder="Project name"/><select value={project.ecosystem} onChange={e=>setProject({...project,ecosystem:e.target.value})}><option>Mangrove</option><option>Seagrass</option><option>Salt Marsh</option><option>Tidal Wetland</option></select><input value={project.location} onChange={e=>setProject({...project,location:e.target.value})} placeholder="Location"/><input type="number" min=".1" value={project.area_hectares} onChange={e=>setProject({...project,area_hectares:e.target.value})} placeholder="Area hectares"/></div><div className="gpsbox card"><b>📍 Mandatory GPS trace</b><p className="muted">Capture 3 high-accuracy readings. Server checks coordinate range, timestamp, stale capture and accuracy warnings.</p><div className="inline"><input value={project.latitude} onChange={e=>setProject({...project,latitude:e.target.value})} placeholder="Latitude"/><input value={project.longitude} onChange={e=>setProject({...project,longitude:e.target.value})} placeholder="Longitude"/><button type="button" onClick={captureGPS} disabled={busy}>{samples?`Sampling ${samples}/3`:'Capture 3 GPS samples'}</button></div><div className="inline"><span className="badge">Accuracy ±{project.gps_accuracy_m||'—'} m</span><span className="badge">{project.captured_at?new Date(project.captured_at).toLocaleString():'Not captured'}</span><button type="button" onClick={validateGPS}>Validate GPS</button></div></div><input type="file" accept="image/*,.pdf" capture="environment" onChange={chooseFile}/>{file&&<div className="proof">Evidence: {file.name} · {(file.size/1024/1024).toFixed(2)} MB · low-bandwidth compression applied to large images</div>}<div className="inline"><button type="button" onClick={hashEvidence}>SHA-256 + geotag</button><button type="button" onClick={pinIPFS}>Pin to IPFS</button><button type="button" onClick={offlineSave}>Save offline pack</button><button type="submit">Create project</button><button type="button" onClick={anchorProject}>Anchor project + GPS</button></div>{project.evidence_hash&&<div className="proof"><span>Evidence SHA-256: {project.evidence_hash}</span><span>GPS proof: {project.capture_proof_hash||'—'}</span><span>IPFS CID: {project.ipfs_cid||'not pinned'}</span></div>}</form></section>}
 {tab==='mrv'&&<><section className="card full"><h2>Measurement, Reporting & Verification</h2><div className="grid2"><select value={mrv.project_id} onChange={e=>{const z=data.projects.find(x=>x.id===Number(e.target.value));setMrv(v=>({...v,project_id:e.target.value,latitude:z?.latitude||v.latitude,longitude:z?.longitude||v.longitude,gps_accuracy_m:z?.gps_accuracy_m||v.gps_accuracy_m,captured_at:z?.captured_at||v.captured_at,evidence_hash:z?.evidence?.hash||v.evidence_hash}))}}><option value="">Select project</option>{data.projects.map(x=><option key={x.id} value={x.id}>#{x.id} {x.name}</option>)}</select><input type="number" value={mrv.reporting_year} onChange={e=>setMrv({...mrv,reporting_year:e.target.value})} placeholder="Reporting year"/><input type="number" min="0" value={mrv.biomass_tonnes_per_hectare} onChange={e=>setMrv({...mrv,biomass_tonnes_per_hectare:e.target.value})} placeholder="Biomass t/ha"/><input type="number" min="0" value={mrv.soil_carbon_tonnes_per_hectare} onChange={e=>setMrv({...mrv,soil_carbon_tonnes_per_hectare:e.target.value})} placeholder="Soil carbon t/ha"/><input type="number" min="0" max="1" step=".01" value={mrv.permanence_factor} onChange={e=>setMrv({...mrv,permanence_factor:e.target.value})} placeholder="Permanence factor"/><input value={mrv.evidence_hash} onChange={e=>setMrv({...mrv,evidence_hash:e.target.value})} placeholder="Evidence SHA-256"/></div><div className="gpsmeta"><span>GPS: {mrv.latitude||'—'}, {mrv.longitude||'—'}</span><span>Accuracy ±{mrv.gps_accuracy_m||'—'} m</span><span>{mrv.captured_at||'—'}</span></div><div className="inline"><button onClick={calculate}>Run digital/AI checks</button><button onClick={submitMRV}>Request human verification</button><button onClick={anchorMRV}>Anchor MRV + GPS on-chain</button></div>{calc&&<div className="result"><b>{calc.indicative_carbon_tonnes} tCO₂e indicative</b><span>Digital risk: {calc.digital_intelligence.risk}</span><span>AI-assisted screening: {calc.digital_intelligence.risk==='LOW'?'LOW':'REVIEW REQUIRED'}</span><span>GPS: {calc.gps_validation.valid?'VALID':'INVALID'} · {calc.digital_intelligence.flags.join(' · ')||'No automated flags'}</span><small>{calc.disclaimer}</small></div>}</section><section className="card full"><h3>Verification status tracker</h3>{data.mrv.map(x=><div className="row" key={x.id}><div><b>MRV #{x.id}</b><small>Project #{x.project_id} · {x.indicative_carbon_tonnes} tCO₂e · submitted {x.submitted_at}</small><small>GPS {x.latitude},{x.longitude} · evidence {x.evidence_hash?'bound':'missing'}</small>{x.verification?.comments&&<small>Verifier feedback: {x.verification.comments}</small>}</div><span className="status">{x.status}</span></div>)}</section></>}
 {tab==='registry'&&<section className="card full"><h2>Public registry</h2>{data.projects.map(x=><div className="row" key={x.id}><div><b>#{x.id} {x.name}</b><small>{x.ecosystem} · {x.location} · {x.area_hectares} ha</small><small>📍 {x.latitude},{x.longitude} · ±{x.gps_accuracy_m??'—'} m · {x.captured_at}</small><small>Evidence: {x.evidence?.hash?'SHA-256 bound':'missing'} · IPFS: {x.evidence?.ipfs_cid||'—'}</small></div><span className="status">{x.status}</span><button onClick={()=>report('project',x.id)}>Generate report</button></div>)}</section>}
 {tab==='training'&&<section className="card full"><h2>Field training and onboarding</h2><p className="muted">Simple step-by-step guidance for NGOs, Panchayats and field teams. Progress is saved on the device.</p>{trainingModules.map(m=><div className="review" key={m[0]}><div><b>{m[0]}. {m[1]}</b><span>{m[2]}</span><small>Checklist: {m[3]}</small></div><button onClick={()=>markTraining(m[0])}>{completed.includes(m[0])?'✓ Completed':'Mark complete'}</button></div>)}<div className="capabilities"><b>Languages:</b> English, Hindi and Marathi interface. <b>Field design:</b> minimal typing, GPS-first capture, image compression and offline queue.</div></section>}
 {tab==='users'&&role==='ADMIN'&&<section className="card full"><h2>User administration · OTP · KYC</h2><input placeholder="KYC reference" value={kycRef} onChange={e=>setKycRef(e.target.value)}/>{data.users.map(u=><div className="row" key={u.id}><div><b>{u.name}</b><small>{u.role} · OTP verified · {u.language}</small></div><span className="status">KYC {u.kyc_status}</span><div className="inline"><button onClick={()=>kyc(u.id,'VERIFIED')}>Verify KYC</button><button onClick={()=>kyc(u.id,'REJECTED')}>Reject</button></div></div>)}</section>}
 {tab==='users'&&role!=='ADMIN'&&<section className="card full"><h2>Role-based access</h2><p>Only administrators can view and manage KYC records. Your role is <b>{role}</b>.</p></section>}
 {tab==='disputes'&&<section className="card full"><h2>Dispute management</h2><div className="grid2"><select value={dispute.project_id} onChange={e=>setDispute({...dispute,project_id:e.target.value})}><option value="">Project (optional)</option>{data.projects.map(x=><option key={x.id} value={x.id}>#{x.id} {x.name}</option>)}</select><select value={dispute.mrv_id} onChange={e=>setDispute({...dispute,mrv_id:e.target.value})}><option value="">MRV (optional)</option>{data.mrv.map(x=><option key={x.id} value={x.id}>MRV #{x.id}</option>)}</select></div><input placeholder="Reason / dispute details" value={dispute.reason} onChange={e=>setDispute({...dispute,reason:e.target.value})}/><button onClick={openDispute}>Open dispute</button>{data.disputes.map(x=><div className="row" key={x.id}><div><b>Dispute #{x.id}</b><small>Project {x.project_id||'—'} · MRV {x.mrv_id||'—'} · {x.reason}</small></div><span className="status">{x.status}</span>{role==='ADMIN'&&<div className="inline"><button onClick={()=>updateDispute(x.id,'IN_REVIEW')}>Review</button><button onClick={()=>updateDispute(x.id,'RESOLVED')}>Resolve</button><button onClick={()=>updateDispute(x.id,'REJECTED')}>Reject</button></div>}</div>)}</section>}
 {tab==='sensors'&&<section className="card full"><h2>IoT / environmental telemetry</h2><p className="muted">Functional simulator for the PDF's future soil-moisture and salinity sensor pathway. Values are timestamped and threshold checked.</p><div className="grid2"><input value={sensor.sensor_id} onChange={e=>setSensor({...sensor,sensor_id:e.target.value})} placeholder="Sensor ID"/><select value={sensor.project_id} onChange={e=>setSensor({...sensor,project_id:e.target.value})}><option value="">Project</option>{data.projects.map(x=><option key={x.id} value={x.id}>#{x.id} {x.name}</option>)}</select><select value={sensor.metric} onChange={e=>setSensor({...sensor,metric:e.target.value,unit:e.target.value==='soil_moisture'?'%':e.target.value==='salinity'?'ppt':'°C'})}><option value="soil_moisture">Soil moisture</option><option value="salinity">Salinity</option><option value="temperature">Temperature</option></select><input type="number" value={sensor.value} onChange={e=>setSensor({...sensor,value:e.target.value})} placeholder="Value"/><input value={sensor.unit} onChange={e=>setSensor({...sensor,unit:e.target.value})} placeholder="Unit"/></div><button onClick={ingestSensor}>Record sensor reading</button>{data.sensors.map(x=><div className="row" key={x.id}><div><b>{x.sensor_id}</b><small>{x.metric}: {x.value} {x.unit} · {x.captured_at}</small></div><span className="status">{x.alerts?.length?x.alerts.join(', '):'NORMAL'}</span></div>)}</section>}
 {tab==='audit'&&<section className="card full"><h2>Audit trail / system integrity</h2>{data.audit.map(x=><div className="row" key={x.id}><div><b>#{x.id} · {x.action}</b><small>{x.at} · {JSON.stringify(x.meta)}</small></div></div>)}</section>}
 {tab==='notifications'&&<section className="card full"><h2>Notifications and feedback</h2>{data.notifications.map(x=><div className="row" key={x.id}><div><b>{x.type}</b><small>{x.created_at} · {JSON.stringify(x).slice(0,300)}</small></div></div>)}</section>}
 {role==='VERIFIER'&&<section className="card full"><h2>Verifier actions · on-ground validation</h2>{pending.map(x=><div className="review" key={x.id}><div><label><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,x.id]:v.filter(i=>i!==x.id))}/> <b>MRV #{x.id}</b></label><span>Project #{x.project_id} · {x.indicative_carbon_tonnes} tCO₂e</span><span>📍 {x.latitude} / {x.longitude} · ±{x.gps_accuracy_m} m · {x.captured_at}</span><span>Evidence {x.evidence_hash?'present':'missing'} · digital risk {x.digital_intelligence?.risk}</span></div><div className="inline"><button onClick={()=>review(x.id,'APPROVE')}>Approve</button><button onClick={()=>review(x.id,'REJECT')}>Reject</button><button onClick={()=>report('mrv',x.id)}>Report</button></div></div>)}<div className="inline"><button onClick={batchQueue} disabled={!selected.length}>Queue selected batch</button><button onClick={()=>batchProcess('APPROVE')} disabled={!selected.length}>Approve selected</button><button onClick={()=>batchProcess('REJECT')} disabled={!selected.length}>Reject selected</button></div>{!pending.length&&<p className="muted">No pending MRVs.</p>}</section>}
 <footer>SIH25038 prototype • React/Vite + Node.js + Solidity/Hardhat/OpenZeppelin • IPFS/SMS are deployment adapters • browser GPS requires HTTPS in deployed environments.</footer>{msg&&<div className="toast">{msg}{busy?' ⏳':''}</div>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);