import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { connectRegistry } from "./blockchain";
import "./styles.css";

const API = import.meta.env.VITE_API_URL || "http://127.0.0.1:3000";
const emptyMRV={project_id:"",reporting_year:new Date().getFullYear(),biomass_tonnes_per_hectare:10,soil_carbon_tonnes_per_hectare:50,permanence_factor:.9,latitude:"",longitude:"",gps_accuracy_m:"",captured_at:"",evidence_hash:""};

function App(){
 const [role,setRole]=useState("NGO"),[projects,setProjects]=useState([]),[mrv,setMrv]=useState([]),[dashboard,setDashboard]=useState({});
 const [project,setProject]=useState({name:"Demo Mangrove Restoration",ecosystem:"Mangrove",location:"Maharashtra Coast",area_hectares:10,latitude:"",longitude:"",gps_accuracy_m:"",evidence_hash:""});
 const [mrvForm,setMrvForm]=useState(emptyMRV),[file,setFile]=useState(null),[message,setMessage]=useState(""),[calculation,setCalculation]=useState(null),[account,setAccount]=useState("");
 const refresh=async()=>{try{const [p,m,d]=await Promise.all([fetch(`${API}/api/projects`).then(r=>r.json()),fetch(`${API}/api/mrv`).then(r=>r.json()),fetch(`${API}/api/dashboard`).then(r=>r.json())]);setProjects(p);setMrv(m);setDashboard(d);if(!mrvForm.project_id&&p[0])setMrvForm(x=>({...x,project_id:p[0].id}));}catch{setMessage(`Start the Node.js API on port 3000 (${API}).`);}};
 useEffect(()=>{refresh()},[]);
 const setGeo=()=>navigator.geolocation?.getCurrentPosition(pos=>setProject(x=>({...x,latitude:pos.coords.latitude.toFixed(6),longitude:pos.coords.longitude.toFixed(6),gps_accuracy_m:pos.coords.accuracy.toFixed(1)})),()=>setMessage("GPS permission was not available."));
 const hashEvidence=async()=>{if(!file)return setMessage("Choose a photo/report first.");const fd=new FormData();fd.append("file",file);const r=await fetch(`${API}/api/evidence/hash`,{method:"POST",body:fd}),d=await r.json();if(!r.ok)return setMessage(d.detail);setProject(x=>({...x,evidence_hash:d.sha256}));setMrvForm(x=>({...x,evidence_hash:d.sha256}));setMessage(`Evidence SHA-256: ${d.sha256.slice(0,18)}…`)};
 const registerProject=async e=>{e.preventDefault();const r=await fetch(`${API}/api/projects`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...project,area_hectares:Number(project.area_hectares)})}),d=await r.json();if(!r.ok)return setMessage(d.detail||"Registration failed");setMrvForm(x=>({...x,project_id:d.id}));setMessage(`Project #${d.id} submitted for verification.`);refresh()};
 const normalized=()=>({...mrvForm,project_id:Number(mrvForm.project_id),reporting_year:Number(mrvForm.reporting_year),biomass_tonnes_per_hectare:Number(mrvForm.biomass_tonnes_per_hectare),soil_carbon_tonnes_per_hectare:Number(mrvForm.soil_carbon_tonnes_per_hectare),permanence_factor:Number(mrvForm.permanence_factor),latitude:mrvForm.latitude?Number(mrvForm.latitude):null,longitude:mrvForm.longitude?Number(mrvForm.longitude):null,gps_accuracy_m:mrvForm.gps_accuracy_m?Number(mrvForm.gps_accuracy_m):null,captured_at:mrvForm.captured_at||new Date().toISOString()});
 const calculate=async()=>{const r=await fetch(`${API}/api/mrv/calculate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(normalized())}),d=await r.json();if(!r.ok)return setMessage(d.detail);setCalculation(d)};
 const submitMRV=async()=>{const r=await fetch(`${API}/api/mrv`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(normalized())}),d=await r.json();if(!r.ok)return setMessage(d.detail);setMessage(`MRV #${d.id} sent to verifier.`);refresh()};
 const review=async(id,decision)=>{const comments=window.prompt(`${decision} comments`,decision==="APPROVE"?"Evidence reviewed and accepted.":"Please correct the evidence.");if(!comments)return;const r=await fetch(`${API}/api/mrv/${id}/verify`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({verifier:"demo-verifier",decision,comments})}),d=await r.json();setMessage(r.ok?`MRV #${id}: ${d.status}`:(d.detail||"Review failed"));refresh()};
 const anchorProject=async()=>{try{const {contract,account:a}=await connectRegistry();setAccount(a);const tx=await contract.registerProject(project.name,project.ecosystem,project.location,project.evidence_hash||"pending-evidence");await tx.wait();setMessage(`Blockchain anchor confirmed: ${tx.hash.slice(0,16)}…`)}catch(e){setMessage(e?.shortMessage||e?.message||"Blockchain transaction failed.")}};
 return <div className="page"><header><div><span className="eyebrow">SIH25038 · CLEAN & GREEN</span><h1>BlueCarbon Registry</h1><p>Hybrid digital intelligence + on-ground human validation for transparent blue-carbon MRV.</p></div><div className="badge">{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Hybrid MRV"}</div></header>
 <nav className="roles">{["NGO","VERIFIER","ADMIN"].map(r=><button className={role===r?"active":""} onClick={()=>setRole(r)} key={r}>{r}</button>)}</nav>
 <section className="stats"><div><small>Projects</small><strong>{dashboard.projects??0}</strong></div><div><small>Area</small><strong>{Number(dashboard.area_hectares||0).toFixed(1)} ha</strong></div><div><small>Pending verification</small><strong>{dashboard.pending_verification??0}</strong></div><div><small>Verified carbon</small><strong>{Number(dashboard.verified_carbon_tonnes||0).toFixed(1)} tCO₂e</strong></div></section>
 <main>
 {role==="NGO"&&<><section className="card"><h2>1 · Submit project evidence</h2><p className="muted">GPS + timestamped evidence directly address the PDF's data-quality safeguards.</p><form onSubmit={registerProject}><input value={project.name} onChange={e=>setProject({...project,name:e.target.value})} placeholder="Project name"/><select value={project.ecosystem} onChange={e=>setProject({...project,ecosystem:e.target.value})}><option>Mangrove</option><option>Seagrass</option><option>Salt Marsh</option><option>Tidal Wetland</option></select><input value={project.location} onChange={e=>setProject({...project,location:e.target.value})} placeholder="Location"/><input type="number" min=".1" step=".1" value={project.area_hectares} onChange={e=>setProject({...project,area_hectares:e.target.value})} placeholder="Area (ha)"/><div className="inline"><input value={project.latitude} onChange={e=>setProject({...project,latitude:e.target.value})} placeholder="Latitude"/><input value={project.longitude} onChange={e=>setProject({...project,longitude:e.target.value})} placeholder="Longitude"/><button type="button" onClick={setGeo}>Use GPS</button></div><input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0])}/><div className="inline"><button type="button" onClick={hashEvidence}>Hash evidence</button><button type="submit">Submit project</button><button type="button" onClick={anchorProject}>Anchor on-chain</button></div></form></section>
 <section className="card"><h2>2 · Measurement & MRV</h2><div className="grid2"><select value={mrvForm.project_id} onChange={e=>setMrvForm({...mrvForm,project_id:e.target.value})}>{projects.map(p=><option key={p.id} value={p.id}>#{p.id} · {p.name}</option>)}</select><input type="number" value={mrvForm.reporting_year} onChange={e=>setMrvForm({...mrvForm,reporting_year:e.target.value})} placeholder="Reporting year"/><input type="number" value={mrvForm.biomass_tonnes_per_hectare} onChange={e=>setMrvForm({...mrvForm,biomass_tonnes_per_hectare:e.target.value})} placeholder="Biomass t/ha"/><input type="number" value={mrvForm.soil_carbon_tonnes_per_hectare} onChange={e=>setMrvForm({...mrvForm,soil_carbon_tonnes_per_hectare:e.target.value})} placeholder="Soil carbon t/ha"/><input type="number" min="0" max="1" step=".01" value={mrvForm.permanence_factor} onChange={e=>setMrvForm({...mrvForm,permanence_factor:e.target.value})} placeholder="Permanence factor"/><input value={mrvForm.evidence_hash} onChange={e=>setMrvForm({...mrvForm,evidence_hash:e.target.value})} placeholder="Evidence SHA-256"/></div><div className="inline"><button onClick={calculate}>Run digital checks</button><button onClick={submitMRV}>Submit for verification</button></div>{calculation&&<div className="result"><b>{calculation.indicative_carbon_tonnes} tCO₂e indicative</b><span>Digital risk: {calculation.digital_intelligence.risk}</span><span>{calculation.digital_intelligence.flags.join(" · ")||"GPS, timestamp and evidence checks passed"}</span></div>}</section></>}
 {role==="VERIFIER"&&<section className="card full"><h2>Verifier work queue</h2><p className="muted">Automated checks support, but do not replace, on-ground human validation.</p>{mrv.filter(x=>x.status==="SUBMITTED").map(x=><div className="review" key={x.id}><div><b>MRV #{x.id}</b><span>Project #{x.project_id}</span><span>{x.indicative_carbon_tonnes} tCO₂e indicative</span><span>Evidence: {x.evidence_hash?x.evidence_hash.slice(0,20)+"…":"missing"}</span></div><div className="inline"><button onClick={()=>review(x.id,"APPROVE")}>Approve</button><button onClick={()=>review(x.id,"REJECT")}>Reject</button></div></div>)}{!mrv.some(x=>x.status==="SUBMITTED")&&<p className="muted">No pending submissions.</p>}</section>}
 {role==="ADMIN"&&<section className="card full"><h2>Admin control centre</h2><div className="result"><span>Roles: NGO / Verifier / Admin</span><span>Pending submissions: {dashboard.pending_verification??0}</span><span>Notifications and dispute/audit trail are retained off-chain</span><span>Future-ready IoT: soil moisture + salinity</span></div><p className="muted">Production KYC/OTP, SMS, multilingual UI, GIS layers and IoT gateways are explicit integration points from the proposal.</p></section>}
 <section className="card full"><h2>Public registry</h2>{projects.map(p=><div className="row" key={p.id}><span>#{p.id} <b>{p.name}</b><small>{p.ecosystem} · {p.location}</small></span><span>{p.area_hectares} ha</span><span className="status">{p.status}</span></div>)}</section><section className="card full"><h2>MRV history</h2>{mrv.map(x=><div className="mrv" key={x.id}><b>MRV #{x.id}</b><span>Project {x.project_id}</span><span>{x.status}</span><span>{x.indicative_carbon_tonnes} tCO₂e</span><span>{x.verification?.comments||"Awaiting verifier"}</span></div>)}</section></main>{message&&<div className="toast">{message}</div>}<footer>SIH25038 prototype · Blockchain provides provenance, not scientific proof. Real credits require approved methodology and independent verification.</footer></div>
}
createRoot(document.getElementById("root")).render(<App/>);
